apiVersion: v1
kind: Service
metadata:
  name: kpen-elb-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:025853706937:certificate/d99a1fb9-296b-484a-836b-b3a7dc1eafe6
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  selector:
    app: kpen-pod
  ports:
    - name: http
      port: 80
      targetPort: 3010
    - name: https
      port: 443
      targetPort: 3010
  type: LoadBalancer