apiVersion: apps/v1
kind: Deployment
metadata:
  name: kworker-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kworker-pod
  template:
    metadata:
      labels:
        app: kworker-pod
    spec:
      containers:
        - name: kworker-app
          image: 472805539381.dkr.ecr.us-east-2.amazonaws.com/kpen-io:latest
          command: ["/usr/app/worker.sh"]
          imagePullPolicy: Always
          resources:
            requests:
              memory: "3G"
            limits:
              memory: "3G"